1552559292420	Delete resource 'RECUPERACION_PYTHON/prueba.py'
